name: WebDriverIO CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git chechout
        uses: actions/checkout@v4
      - name: SetUp NodeJs -20
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - run: npm ci
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
            filename: tests/performancetest.js
        
      
      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlreports
          path: summary.html
          compression-level: 0 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
      
